/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quique.proyectomaven;

import javax.swing.JFileChooser;

/**
 *
 * @author quique
 */

/**
 * 
 * @param urlpath Es la url del repositorio al que queremos hacer el clonado.
 * @param urlclone Es la url del repositorio remoto del que queremos hacer el clonado.
 * @param elegirpath Es un JFileChooser de la paleta gráfica que te abre una ventana para poder seleccionar la ruta del repositorio.
 */
public class Clonado extends javax.swing.JFrame {

    static String urlpath;
    static String urlclone;
    static JFileChooser elegirpath;
    Menu men = new Menu();
    
    
    //Constructor en el que inicializamos el repositorio y creamos un objeto de tipo JFileChooser
    public Clonado() {
        initComponents();

        elegirpath = new JFileChooser();
        
        //Con este método restringimos al jfilechooser para que solo puedas seleccionar directorios.
        elegirpath.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        path = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        url = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Introduzca la url del repositorio");

        path.setText("...");
        path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathActionPerformed(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aceptar)
                        .addGap(18, 18, 18)
                        .addComponent(cancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(path)
                        .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param evt es la ejecución de la acción del botón para seleccionar la ruta
     */
    private void pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathActionPerformed

        //Abrimos el joptionchooser y segun seleccionemos los botones "Aceptar" o "Cancelar" 
        //Va a salir del programa o recoger la ruta.
        int seleccion = elegirpath.showDialog(null, "Abrir");
        switch (seleccion) {

            case JFileChooser.APPROVE_OPTION:
                urlpath = elegirpath.getSelectedFile().getAbsolutePath();
                //System out para ver que pilla la ruta
                System.out.println(urlpath);
                break;
            case JFileChooser.CANCEL_OPTION:
                break;
            default:
                System.out.println("Error.");
        }
    }//GEN-LAST:event_pathActionPerformed

    /**
     * @param evt ActionEvent que captura la acción del botón cancelar.
     *  Este action performed pone oculta esta ventana y hace visible la ventana menu
     */
    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.setVisible(false);
        men.setVisible(true);
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param evt ActionEvent que captura la acción del boton aceptar.
     * @param url JTextField en el que introducimos la ruta del repositorio de GitHub
     *  Este action performed a la variable urlclone le pasa la url del repositorio remoto que introducimos en el jtextfield
     *  Llamamos al método hacer clonado y le pasamos la url del repositorio remoto y la url del directorio
     */
    
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        urlclone = url.getText();
        this.setVisible(false);

        Codigo.hacerClonado(url.getText(), urlpath);
        urlpath = null;
        men.setVisible(true);
    }//GEN-LAST:event_aceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton path;
    static javax.swing.JTextField url;
    // End of variables declaration//GEN-END:variables

}
